### ISSUE TITLE
Connection gets forcibly closed

### ISSUE THREAD

**Issue by mhtracking** [NexaAI/nexa-sdk#795]
(venv) PS D:\Moaz Haroon\nexa-sdk> nexa infer NexaAI/Qwen3-VL-4B-Thinking-GGUF
Migration completed.
model not found, start download
downloading  74% |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                               | (2.9/3.9 GB, 4.3 MB/s) [7m59s:3m56s] 
Error: read tcp 192.168.0.119:58232->52.219.113.106:443: wsarecv: An existing connection was forcibly closed by the remote host.
✔  Download success!
Error: open C:\Users\PC_NAME\.cache\nexa.ai\nexa_sdk\models\NexaAI\Qwen3-VL-4B-Thinking-GGUF\nexa.manifest: The system cannot find the file specified.
(venv) PS D:\Moaz Haroon\nexa-sdk> 

I was following the guide on this page:
https://sdk.nexa.ai/model/Qwen3-VL-4B-Thinking

**Comment by vinovo** [comment]
This is likely due to some network instability, rather than a Nexa SDK error. If you try `nexa pull NexaAI/Qwen3-VL-4B-Thinking-GGUF` again, will it successfully download the model? Does it fails at the same percentage on the second run?

**Comment by mhtracking** [comment]
I think my network is stable. If I try nexa pull NexaAI/Qwen3-VL-4B-Thinking-GGUF again, it still fails (restarts the download) and it does not fail at a particular percentage everytime, but at points. Issue is still not fixed.
Even is the network is not stable should the downloads be managed like they are in hugging face? Manage crashes?
Please fix this

**Comment by mengshengwu** [comment]
> I think my network is stable. If I try nexa pull NexaAI/Qwen3-VL-4B-Thinking-GGUF again, it still fails (restarts the download) and it does not fail at a particular percentage everytime, but at points. Issue is still not fixed. Even is the network is not stable should the downloads be managed like they are in hugging face? Manage crashes? Please fix this
Thanks for the detailed report!

The issue where download failures were not correctly detected or reported has been resolved.
Additionally, resumable download support is now being tracked separately in:
👉 [#803](https://github.com/NexaAI/nexa-sdk/issues/803)

Please pull the latest version once the next release is published — it will include more robust error handling for interrupted or unstable connections.

**Comment by mhtracking** [comment]
Fixed thanks.

**Comment by mhtracking** [comment]
sorry it is not fixed. it gave the same error. worked on a smaller model. but larger model still face this issue.

(venv) PS D:\newNexa\nexa-sdk\runner\build> .\nexa-cli.exe list

┌──────────────────────────┬─────────┬────────┐

│ NAME                     │ SIZE    │ QUANTS │

├──────────────────────────┼─────────┼────────┤

│ ggml-org/Qwen3-1.7B-GGUF │ 1.2 GiB │ Q4_K_M │

└──────────────────────────┴─────────┴────────┘

(venv) PS D:\newNexa\nexa-sdk\runner\build> .\nexa-cli.exe pull NexaAI/Qwen3-VL-4B-Instruct-GGUF

downloading  49% |███████████████████████████████████                                      | (1.9/3.9 GB, 12 MB/s) [5m48s:2m40s] 

Error: read tcp 192.168.0.119:51347->52.219.121.50:443: wsarecv: An existing connection was forcibly closed by the remote host.  

(venv) PS D:\newNexa\nexa-sdk\runner\build> 




here are the instructions I followed to build the CLi:
https://github.com/mhtracking/nexa-build-instructions/tree/main

**Comment by mengshengwu** [comment]
Thanks for the follow-up and for sharing the detailed logs!

1. The recent fix addressed the issue where **download failures were not correctly detected or reported** — so failed transfers should now surface proper error messages instead of silently succeeding.

2. From the behavior you described (`wsarecv: connection was forcibly closed`), this still looks like a **network stability issue**.
   At present, the SDK **does not yet include retry or resumable** logic — both features are being tracked under [(https://github.com/NexaAI/nexa-sdk/issues/803)](https://github.com/NexaAI/nexa-sdk/issues/803) and are planned for a future release.

3. As a workaround, you can manually download the model first via Hugging Face, then import it locally:

   ```bash
   hf download NexaAI/Qwen3-VL-4B-Instruct-GGUF
   nexa pull --mode-hub localfs --local-path /path/to/hfdownload
   ```

This approach avoids repeated large downloads in case of unstable network connections.

**Comment by RemiliaForever** [comment]
track by #803.
